// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TWMSServer;

#nullable disable

namespace TWMSServer.Migrations
{
    [DbContext(typeof(TWMSServerContext))]
    [Migration("20250529135025_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TWMSServer.Model.AssetClass", b =>
                {
                    b.Property<int>("AssetClassId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AssetClassId"));

                    b.Property<string>("AssetClassLongDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AssetClassShortDesc")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("Status")
                        .HasMaxLength(50)
                        .HasColumnType("bit");

                    b.HasKey("AssetClassId");

                    b.ToTable("tblAssets_Classes");
                });

            modelBuilder.Entity("TWMSServer.Model.DepartmentRoleAssignment", b =>
                {
                    b.Property<int>("DepartmentRoleAssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentRoleAssignmentId"));

                    b.Property<string>("DepartmentCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmployeeNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepartmentRoleAssignmentId");

                    b.ToTable("DepartmentRoleAssignments");
                });

            modelBuilder.Entity("TWMSServer.Model.EmailAttachment", b =>
                {
                    b.Property<int>("EmailAttachmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmailAttachmentId"));

                    b.Property<string>("ContentType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EmailDataId")
                        .HasColumnType("int");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OriginalFileName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmailAttachmentId");

                    b.HasIndex("EmailDataId");

                    b.ToTable("EmailAttachment");
                });

            modelBuilder.Entity("TWMSServer.Model.EmailData", b =>
                {
                    b.Property<int>("EmailDataId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmailDataId"));

                    b.Property<string>("BCCRecipients")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CCRecipients")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("SentSuccessfullyAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemplateDataRaw")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TemplateName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ToRecipients")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmailDataId");

                    b.ToTable("Emails");
                });

            modelBuilder.Entity("TWMSServer.Model.JobPlansHeader", b =>
                {
                    b.Property<int>("JobPlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("JobPlanId");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobPlanId"));

                    b.Property<int>("AssetClassId")
                        .HasMaxLength(25)
                        .HasColumnType("int")
                        .HasColumnName("AssetClassId");

                    b.Property<string>("AssetClassShortDesc")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("AssetClassShortDesc");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateModified")
                        .HasColumnType("datetime2");

                    b.Property<string>("JobPlanLongDesc")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("JobPlanLongDesc");

                    b.Property<string>("JobPlanShortDesc")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)")
                        .HasColumnName("JobPlanShortDesc");

                    b.Property<bool>("JobPlanStatus")
                        .HasMaxLength(25)
                        .HasColumnType("bit")
                        .HasColumnName("JobPlanStatus");

                    b.Property<string>("ModifiedBy")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("JobPlanId");

                    b.ToTable("tblJob_Plans_Headers");
                });

            modelBuilder.Entity("TWMSServer.Model.JobPlansLine", b =>
                {
                    b.Property<int>("JobPlanLineId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("Job_Plan_Line_ID");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobPlanLineId"));

                    b.Property<int>("JobPlanId")
                        .HasColumnType("int")
                        .HasColumnName("Job_Plan_ID");

                    b.Property<string>("JobPlanLineDesc")
                        .IsRequired()
                        .HasMaxLength(2147483647)
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("Job_Plan_Line_Desc");

                    b.Property<long>("JobPlanLineNo")
                        .HasColumnType("bigint")
                        .HasColumnName("Job_Plan_Line_No");

                    b.HasKey("JobPlanLineId");

                    b.HasIndex("JobPlanId");

                    b.ToTable("tblJob_Plans_Lines");
                });

            modelBuilder.Entity("TWMSServer.Model.JobSchedule", b =>
                {
                    b.Property<int>("JobScheduleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("JobScheduleId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CronExpression")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("LastRun")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("JobScheduleId");

                    b.ToTable("JobSchedules");
                });

            modelBuilder.Entity("TWMSServer.Model.SystemRoleAssignment", b =>
                {
                    b.Property<int>("SystemRoleAssignmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SystemRoleAssignmentId"));

                    b.Property<string>("EmployeeNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SystemRoleAssignmentId");

                    b.ToTable("SystemRoleAssignments");
                });

            modelBuilder.Entity("TWMSServer.Model.WorkOrder", b =>
                {
                    b.Property<int>("WorkOrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("WorkOrderId"));

                    b.Property<string>("Account")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Area")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AssociatedWONumber")
                        .HasColumnType("int");

                    b.Property<string>("CostCentre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("JobNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("JobTypeSubCategory")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<string>("RequestedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceDocumentNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SourceDocumentType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("WorkOrderId");

                    b.ToTable("tblWorkOrderHeader");
                });

            modelBuilder.Entity("TWMSServer.Model.EmailAttachment", b =>
                {
                    b.HasOne("TWMSServer.Model.EmailData", null)
                        .WithMany("Attachments")
                        .HasForeignKey("EmailDataId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("TWMSServer.Model.JobPlansLine", b =>
                {
                    b.HasOne("TWMSServer.Model.JobPlansHeader", "JobPlansHeader")
                        .WithMany("JobPlansLines")
                        .HasForeignKey("JobPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobPlansHeader");
                });

            modelBuilder.Entity("TWMSServer.Model.EmailData", b =>
                {
                    b.Navigation("Attachments");
                });

            modelBuilder.Entity("TWMSServer.Model.JobPlansHeader", b =>
                {
                    b.Navigation("JobPlansLines");
                });
#pragma warning restore 612, 618
        }
    }
}
